name : 'Terraform Github Actions'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: Terraform
    runs-on:  ubuntu-latest

    env: 
      AWS_ACCESS_KEY_ID:      ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN:      ${{secrets.AWS_SESSION_TOKEN}}

      AWS_REGION: ap-northeast-1

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run:  terraform init

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
